[project]
name = "perplexity_sagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.118.0",
    "crewai-tools>=0.44.0",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.7.1",
]
